### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by hakhsin** [wuruoyun/vue-component-lib-starter#1]
Hi, I created a vue ui library with this repo. I added my library in another project as local dependency. When I build server in browser I get this error:
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```
What do I do?

**Comment by climberger** [comment]
Did you find a solution for this problem? I had the same issue when building my own component library.

**Comment by hakhsin** [comment]
Hi @climberger, I solved it but I has forgot it now. I thought a little bit for remember it but I don't remember. I'm sorry!

**Comment by wuruoyun** [comment]
Closing this issue as the project has been updated to Vue3 and Vite. This issue is likely no longer relevant.
