### ISSUE TITLE
Types definition not working

### ISSUE THREAD

**Issue by miquelromero** [wuruoyun/vue-component-lib-starter#38]
The way types path is defined in package.json doesn't seem to work.

I managed to fix it by doing what is mentioned in the following answer.
https://stackoverflow.com/a/76212193/19632946

**Comment by megasanjay** [comment]
Saved me a lot of time. Thanks for coming back and commenting on this issue!

**Comment by wuruoyun** [comment]
Thank you @miquelromero for reporting the issue. The issue has been resolved.
