### ISSUE TITLE
components not able to access scss mixins and variables

### ISSUE THREAD

**Issue by ShivamChaurasia** [wuruoyun/vue-component-lib-starter#4]
Hi, I'm trying to create a component library using this project.
Most of my components use Sass mixins and variables.
How can I import a global CSS for all components to be able to access?

**Comment by wuruoyun** [comment]
Added a simple example for global styling. Please refer to the updated README. Thanks.

**Comment by ShivamChaurasia** [comment]
Thanks for the update!
but using sass variables still doesn't work somehow.

![image](https://user-images.githubusercontent.com/17452741/86016298-e57c3b80-ba22-11ea-8929-9512732ad046.png)
![image](https://user-images.githubusercontent.com/17452741/86016323-ef9e3a00-ba22-11ea-8d9f-db5084e72180.png)

**Comment by wlafrance** [comment]
I am seeing similar issues.  Looks like the *.scss  files are not actually getting compiled (parsed) and such. This article talks about it, but I have not been able to get the desired results.  For example, change the assets **global-style border color to RED** or such.. to confirm it is getting updated...   https://cli.vuejs.org/guide/css.html#referencing-assets

**Comment by wuruoyun** [comment]
Closing this issue as the project has been updated to Vue3 and Vite. The project now process both component level and library level SCSS into /dist/style.css. Please also refer to the section related to styling in README.md.
